### ISSUE TITLE
KeyError: 'Authentication' on Win10, WSLv2, AlpineWSL, Python3.9.5

### ISSUE THREAD

**Issue by 4SiB** [ynop/togglore#6]
This not work :(
Win10, WSLv2, AlpineWSL, Python3.9.5

```
SIB-E5480:~/ynop-togglore/togglore# python3 run.py
usage: run.py [-h] {range,thisyear,thismonth,thisweek,today,month,since} ...
run.py: error: the following arguments are required: command
SIB-E5480:~/ynop-togglore/togglore#
SIB-E5480:~/ynop-togglore/togglore#
SIB-E5480:~/ynop-togglore/togglore#
SIB-E5480:~/ynop-togglore/togglore# python3 run.py today
Traceback (most recent call last):
  File "/root/ynop-togglore/togglore/run.py", line 27, in <module>
    client = togglore.Togglore()
  File "/root/ynop-togglore/togglore/togglore/__init__.py", line 11, in __init__
    self.cfg = config.Config.read_from_file(config_path)
  File "/root/ynop-togglore/togglore/togglore/config.py", line 27, in read_from_file
    api_key = cfg['Authentication']['API_KEY']
  File "/usr/lib/python3.9/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'Authentication'
SIB-E5480:~/ynop-togglore/togglore#

```

**Comment by 4SiB** [comment]
Fresh installation AlpineWSL 3.14.0

```
apk update
apk upgrade
apk add python3 git
cat .togglore > ~/.togglore
cd
git clone https://github.com/ynop/togglore.git
cd togglore/
python3 run.py
time python3 run.py since 2021.10.1
Hours to do: 43.20h (6.00 days)
Hours worked: 29.56h (4.11 days)
Difference: -13.64h (-1.89 days)
real    17m 43.61s
user    0m 0.13s
sys     0m 0.00s

```
