### ISSUE TITLE
It's stop work. Toggl API change URL's, the ynop not fix them.

### ISSUE THREAD

**Issue by 4SiB** [ynop/togglore#9]
```
python3 run.py since 2021.10.1
Traceback (most recent call last):
  File "/root/togglore/run.py", line 45, in <module>
    actual, expected = client.diff(utils.DateRange.since(args.since))
  File "/root/togglore/togglore/__init__.py", line 17, in diff
    actual_hours = utils.sum_time_of_entries(self.toggle.time_entries(date_range))
  File "/root/togglore/togglore/toggl.py", line 46, in time_entries
    response = self.request(
  File "/root/togglore/togglore/toggl.py", line 33, in request
    response = urllib.request.urlopen(req).read()
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone
Command exited with non-zero status 1
```

**Comment by 4SiB** [comment]
FIX

./togglore/toggl.py
```
- 'https://toggl.com/reports/api/v2/details?workspace_id={}&since={}&until={}&user_agent=togglore&page={}'.format(
+ 'https://api.track.toggl.com/reports/api/v2/details?workspace_id={}&since={}&until={}&user_agent=togglore&page={}'.format(
```
